[package]
name = "hello_world"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hello_world_app = { path = "../app" }

[build-dependencies]
gear-wasm-builder.workspace = true
sails-idl-gen.workspace = true
hello_world_app = { path = "../app" }
