[workspace]
resolver = "2"

members = [
    "app", "wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[workspace.dependencies]
gstd = "*"
gear-wasm-builder = "*"
sails-idl-gen = "*"
sails-rs = "*"
