[package]
name = "counter_proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
counter_proxy_app = { path = "../app" }

[build-dependencies]
gear-wasm-builder.workspace = true
sails-idl-gen.workspace = true
counter_proxy_app = { path = "../app" }
