[package]
name = "lesson_03_part_02_app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gstd.workspace = true
sails-rs.workspace = true
vft-service.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
